### ISSUE TITLE
PDF does not render properly, macOS Monterey 12.3.1

### ISSUE THREAD

**Issue by nafeu** [caickdias/invoice-generator#2]
My PDF runs like this when I use `node index.js`

![image](https://user-images.githubusercontent.com/6453335/186669207-d2e2d85f-2b8e-42e2-841d-8d2df2169a0b.png)

**Comment by caickdias** [comment]
It seems Windows DPI is around 90, while unix systems is 72. I fixed it using CSS property 'zoom: 0.753' if not on Windows. It worked on Ubuntu 22.04, please tell me if it works on your OS aswell!

**Comment by nafeu** [comment]
Looks like rendering works fine now, thank you!
